### PR TITLE
to svelte4

### PR DESCRIPTION
**Pull request by asukaminato0721**

### CODE REVIEW

**Comment by lilydjwg** [comment]
Can you figure out how to use newer version of nodejs on Vercel?

**Comment by lilydjwg** [comment]
OK, I've figured it out.

**Comment by lilydjwg** [comment]
It doesn't load correctly. I've rollbacked the deployment.

**Comment by lilydjwg** [comment]
`onMount` isn't called after this change. Can you figure out a fix?

**Comment by asukaminato0721** [comment]
> `onMount` isn't called after this change. Can you figure out a fix?

I guess this: https://svelte.dev/docs/v4-migration-guide#stricter-types-for-svelte-functions

> onMount now shows a type error if you return a function asynchronously from it, because this is likely a bug in your code where you expect the callback to be called on destroy, which it will only do for synchronously returned functions

but as this https://github.com/sveltejs/svelte/pull/8136 said, it only has a relationship to `return async`

**Comment by asukaminato0721** [comment]
I am not sure if the below code works.

```js
  onMount(() => {
    do_hash_search();
    while (true) {
      try {
        fetch(`${LUOXU_URL}/groups`)
          .then((res) => res.json())
          .then((json) => {
            groups = json.groups;
            need_update_title = true;
          });
        if (!group) {
          group = "";
        }
        break;
      } catch (e) {
        console.error("failed to fetch group info, will retry", e);
        sleep(1000).then(() => {});
      }
    }
  });
```

**Comment by lilydjwg** [comment]
There is no error, and there is no function returned.

**Comment by asukaminato0721** [comment]
is there a minimal example to test locally? ~~Or maybe propose an issue to Svelte~~ .

**Comment by lilydjwg** [comment]
Not yet. You can try to create one.

**Comment by lilydjwg** [comment]
I've reverted this. I'll try again after the issue is resolved.

**Pull request merged**
